### ISSUE TITLE
Program running twice when importing hpOneView

### ISSUE THREAD

**Issue by andrefaranha** [HewlettPackard/python-hpOneView#177] opened 2016-08-19 18:04 UTC
We are facing a weird problem when using python-hpOneView. All statements are running twice after adding the import.

Example:

**Before importing:**
```
print 'hello'
```

Output:
```
$ python test.py 
hello
```

**After importing:**
```
from hpOneView.oneview_client import OneViewClient

print 'hello'
```

Expected Output:
```
$ python test.py 
hello
```

Actual Output:
```
$ python test.py 
hello
hello
```

UPDATE:

It worked as expected after adding `if __name__ == '__main__'`:
```
from hpOneView.oneview_client import OneViewClient

if __name__ == '__main__':
    print 'hello'
```

Output:
```
$ python test.py 
hello

**Comment by marikrg** [comment] 2016-08-19 20:37
Which python version and operating system are you using?

**Comment by marikrg** [comment] 2016-08-19 21:13
@andrefaranha I could reproduce the issue, thank you for reporting it.

**Comment by andrefaranha** [comment] 2016-08-22 19:43
Sorry for the late response. I'm using python 2.7.12

**Comment by marikrg** [comment] 2016-08-29 19:43
After some research I realised that it is not a bug on the SDK, it happens after enabling the support for renamed standard library modules using the future library.

Basically, the same behaviour occurs replacing the import:

```python
from hpOneView.oneview_client import OneViewClient
```

by the following lines:

```python
from future import standard_library
standard_library.install_aliases()
```

There is an internal module on Python named **test**, that is being imported when the install_aliases is called. You can check the code at: https://github.com/PythonCharmers/python-future/blob/master/src/future/standard_library/__init__.py#L483

I suggest renaming your module from **test** to something else, to avoid the conflict with the Python's internal module.

**Comment by tiagomtotti** [comment] 2016-09-01 19:58
@andrefaranha have you seen @marikrg comment about this Issue ? Did it solve your problem ?

**Comment by tiagomtotti** [comment] 2016-09-08 17:47
@andrefaranha  since we didn't have a response, I'll close the issue.
If you find that this problem still happens after applying the steps suggested by @marikrg,  please reopen this issue.

**Closed by tiagomtotti** 2016-09-08 17:47 UTC
